version: '3.3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loteria
    volumes:
      - "./.data/db:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080